#Normalizing Categorical Features

In [4]:
import pandas as pd
from sklearn import preprocessing

In [5]:
data = {'price':[492,286,598,487,541,429]}

In [7]:
s = pd.DataFrame(data)

In [8]:
min_max_normalizer = preprocessing.MinMaxScaler()

In [9]:
scaled_data = min_max_normalizer.fit_transform(s)

In [11]:
scaled_data #maximm value transforms to 1 and minimum value transforms to 0
#Xnew = (X(i) - min(X))/max(X) - min(X)

array([[0.66025641],
       [0.        ],
       [1.        ],
       [0.64423077],
       [0.81730769],
       [0.45833333]])

In [13]:
p = pd.DataFrame(scaled_data)

In [14]:
data

{'price': [492, 286, 598, 487, 541, 429]}

In [16]:
s = pd.DataFrame(data)

In [24]:
min_max_normalizer = preprocessing.scale(s)
min_max_normalizer #Z = (X-mean(X))/StdDev(X)

array([[ 0.20223565],
       [-1.89829597],
       [ 1.28309173],
       [ 0.15125187],
       [ 0.70187667],
       [-0.44015994]])

In [25]:
a = pd.DataFrame(min_max_normalizer,columns = ['price'])

In [26]:
a

price
0  0.202236
1 -1.898296
2  1.283092
3  0.151252
4  0.701877
5 -0.440160

#StandardScaler -Standardize the features by removing the mean and scaling to unit varaince.The Standard Score of a sample x is z = (x-u)/s

copy boolean,optional,default it is True,if False try to avoid a copy and do inpace scaling instead.

with_mean boolean,optional,True by default.

If True,center the data before scaing.

with_std boolean,True by default,if True scale the data to unit varaince(or equivvalently unit standard deviation


In [29]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [30]:
data = np.array([[0,0],[0,0],[1,1],[1,1]])

In [31]:
data

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1]])

In [32]:
scaler = StandardScaler()

In [33]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [35]:
scaler.mean_

array([0.5, 0.5])

In [36]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])