In [2]:
import numpy as np

In [19]:
a = np.array((1,'2.6',3))

In [20]:
a

array(['1', '2.6', '3'], dtype='<U11')

In [21]:
print(a)

['1' '2.6' '3']


In [6]:
a = [1,2,3,4]
a[2]

3

In [7]:
import array as ar

In [19]:
a = ar.array('d',[1,2,3])

In [20]:
a

array('d', [1.0, 2.0, 3.0])

In [21]:
print(a)

array('d', [1.0, 2.0, 3.0])


In [24]:
import numpy as np
a = np.array([1,2,3])

In [25]:
a

array([1, 2, 3])

In [26]:
b = np.array([[1,2,3],[4,5,6]])

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
print(b)

[[1 2 3]
 [4 5 6]]


In [30]:
import numpy as np
import sys
S = range(1000) 
print(sys.getsizeof(10)*len(S)) 

28000


In [32]:
D = np.arange(1000) 
print(D.size * D.itemsize)

4000


In [47]:
import time
import sys
import numpy as np
SIZE = 1000
L1 = range(SIZE)
L2 = range(SIZE)
start = time.time() 
result = [(x,y) for x,y in zip(L1,L2)]
print(result)
print((time.time()-start)*1000) 

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 1

In [48]:
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)
start = time.time()
result = A1 + A2
print(result)
print((time.time()-start)*1000)

[   0    2    4    6    8   10   12   14   16   18   20   22   24   26
   28   30   32   34   36   38   40   42   44   46   48   50   52   54
   56   58   60   62   64   66   68   70   72   74   76   78   80   82
   84   86   88   90   92   94   96   98  100  102  104  106  108  110
  112  114  116  118  120  122  124  126  128  130  132  134  136  138
  140  142  144  146  148  150  152  154  156  158  160  162  164  166
  168  170  172  174  176  178  180  182  184  186  188  190  192  194
  196  198  200  202  204  206  208  210  212  214  216  218  220  222
  224  226  228  230  232  234  236  238  240  242  244  246  248  250
  252  254  256  258  260  262  264  266  268  270  272  274  276  278
  280  282  284  286  288  290  292  294  296  298  300  302  304  306
  308  310  312  314  316  318  320  322  324  326  328  330  332  334
  336  338  340  342  344  346  348  350  352  354  356  358  360  362
  364  366  368  370  372  374  376  378  380  382  384  386  388  390
  392 

In [54]:
a = np.array([1,2,3])
a[0:]

array([1, 2, 3])

In [58]:
a = np.array([[1,2,3,4],[3,4,5,6]]) #axis 0 - rows and axis 1 as columns
a[0:]

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [59]:
a[:1]

array([[1, 2, 3, 4]])

In [61]:
a[0:,2]

array([3, 5])

In [66]:
a[0]
a[0,2]

3

In [80]:
a=np.linspace(1.,5.,6)

In [81]:
a

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [79]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [90]:
a = np.array([[1,2,3],[4,5,6],[5,8,9]])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [5 8 9]]
2
4
int32
9
(3, 3)


In [92]:
data = np.random.rand(2, 3)
data

array([[0.96694731, 0.7986299 , 0.62522303],
       [0.80695854, 0.798307  , 0.21249195]])

In [93]:
data + data

array([[1.93389462, 1.5972598 , 1.25044606],
       [1.61391707, 1.59661401, 0.42498389]])

In [94]:
data * data

array([[0.9349871 , 0.63780972, 0.39090384],
       [0.65118208, 0.63729407, 0.04515283]])

In [95]:
data - data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.]])

In [97]:
data % data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
data1 = np.array([[-1,23,25],[4,5,6]])
data1 > data

array([[False,  True,  True],
       [ True,  True,  True]])