In [1]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [2]:
data = np.random.randn(7, 4)

In [3]:
data

array([[-0.24515542,  0.11767491,  0.28343845, -0.32356475],
       [-1.1427546 ,  0.60630799, -0.37562008, -0.22204284],
       [ 1.75505869, -1.00703616,  0.01377714, -0.57582023],
       [ 1.69181988, -1.29592779,  2.08882477, -1.78379975],
       [-2.01141408,  1.41022616,  0.43604051,  0.06825787],
       [ 0.49458538,  0.72542211,  0.65507965,  0.85780278],
       [-0.17782003,  0.26429257, -0.53889249,  0.43894616]])

In [4]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data[names == 'Bob']

array([[-0.24515542,  0.11767491,  0.28343845, -0.32356475],
       [ 1.69181988, -1.29592779,  2.08882477, -1.78379975]])

In [9]:
data[names == 'Joe']

array([[-1.1427546 ,  0.60630799, -0.37562008, -0.22204284],
       [ 0.49458538,  0.72542211,  0.65507965,  0.85780278],
       [-0.17782003,  0.26429257, -0.53889249,  0.43894616]])

In [10]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [12]:
data[~(names == 'Bob')] 

array([[-1.1427546 ,  0.60630799, -0.37562008, -0.22204284],
       [ 1.75505869, -1.00703616,  0.01377714, -0.57582023],
       [-2.01141408,  1.41022616,  0.43604051,  0.06825787],
       [ 0.49458538,  0.72542211,  0.65507965,  0.85780278],
       [-0.17782003,  0.26429257, -0.53889249,  0.43894616]])

In [16]:
print(names)
mask = (names == 'Bob') | (names == 'Will')

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [17]:
mask

array([ True, False,  True,  True,  True, False, False])

In [18]:
data

array([[-0.24515542,  0.11767491,  0.28343845, -0.32356475],
       [-1.1427546 ,  0.60630799, -0.37562008, -0.22204284],
       [ 1.75505869, -1.00703616,  0.01377714, -0.57582023],
       [ 1.69181988, -1.29592779,  2.08882477, -1.78379975],
       [-2.01141408,  1.41022616,  0.43604051,  0.06825787],
       [ 0.49458538,  0.72542211,  0.65507965,  0.85780278],
       [-0.17782003,  0.26429257, -0.53889249,  0.43894616]])

In [19]:
data[mask]

array([[-0.24515542,  0.11767491,  0.28343845, -0.32356475],
       [ 1.75505869, -1.00703616,  0.01377714, -0.57582023],
       [ 1.69181988, -1.29592779,  2.08882477, -1.78379975],
       [-2.01141408,  1.41022616,  0.43604051,  0.06825787]])

In [20]:
data[data < 0 ] = 0
data

array([[0.        , 0.11767491, 0.28343845, 0.        ],
       [0.        , 0.60630799, 0.        , 0.        ],
       [1.75505869, 0.        , 0.01377714, 0.        ],
       [1.69181988, 0.        , 2.08882477, 0.        ],
       [0.        , 1.41022616, 0.43604051, 0.06825787],
       [0.49458538, 0.72542211, 0.65507965, 0.85780278],
       [0.        , 0.26429257, 0.        , 0.43894616]])

In [25]:
data[names == 'Bob',2:]

array([[0.28343845, 0.        ],
       [2.08882477, 0.        ]])

In [14]:
arr

array([[1.11258446e-306, 1.60219035e-306, 8.90070286e-308,
        2.37151510e-322],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [15]:
arr[[4,3,0,6]]

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.11258446e-306, 1.60219035e-306, 8.90070286e-308,
        2.37151510e-322],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [1]:
import numpy as np
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

In [2]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
arr + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [4]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
 arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

In [10]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [12]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [14]:
a = np.arange(10)

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[5]

5

In [17]:
a[5:8]

array([5, 6, 7])

In [18]:
a[5:8] = 10

In [19]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [20]:
b = a[5:8]

In [21]:
b

array([10, 10, 10])

In [22]:
b[1] = 15

In [23]:
a

array([ 0,  1,  2,  3,  4, 10, 15, 10,  8,  9])

In [24]:
b[:] = 33

In [25]:
a

array([ 0,  1,  2,  3,  4, 33, 33, 33,  8,  9])

In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

In [27]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [30]:
arr2d[1, :2]

array([4, 5])

In [31]:
arr2d[:2, 2]

array([3, 6])

In [32]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [33]:
arr2d[:2, 1:] = 0

In [34]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [26]:
arr = np.empty((8, 4))
arr

array([[       nan, 4.941e-324, 4.684e-321, 1.976e-323],
       [5.257e-321, 2.031e-321, 3.834e-321, 2.031e-321],
       [4.921e-321, 2.031e-321, 2.885e-321, 2.031e-321],
       [4.980e-321, 2.031e-321, 4.684e-321, 2.031e-321],
       [4.684e-321, 1.976e-323, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000]])

In [28]:
for i in range(8):  
    arr[i] = i

In [29]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [33]:
arr[[4,5]] 

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [35]:
import random
from random import randint
for i in range(10):
    print(randint(2,10))

4
8
9
4
9
8
6
3
5
6
