In [7]:
import numpy as np
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

 empty_like : Return an empty array with shape and type of input.
 ones_like : Return an array of ones with shape and type of input.
 zeros_like : Return an array of zeros with shape and type of input.
 full_like : Return a new array with shape of input filled with value.
 empty : Return a new uninitialized array.
 ones : Return a new array setting values to one.
 zeros : Return a new array setting values to zero.
 full : Return a new array of given shape filled with value

In [9]:
import numpy as np
a = np.ones_like((2,2))
a

array([1, 1])

In [15]:
x = np.arange(6)
x = x.reshape((2, 3))
print(x)
np.ones_like(x)
#np.ones_like(x)

[[0 1 2]
 [3 4 5]]


array([[1, 1, 1],
       [1, 1, 1]])

In [2]:
import numpy as np
print(np.zeros((3,2))) #2d array
print(np.zeros(2)) # 1d array

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0.]


In [5]:
print(np.zeros_like((3,2))) 

[0 0]


In [17]:
print(np.full((3, 2), 5))

[[5 5]
 [5 5]
 [5 5]]


In [19]:
x = np.arange(6)
print(x)
np.full_like(x, 1)

[0 1 2 3 4 5]


array([1, 1, 1, 1, 1, 1])

In [24]:
#empty creates an array whose initial content is random and depends on the state of the memory
np.empty([1, 2])

array([[1.0609979e-313, 1.0609979e-313]])

In [29]:
#Return a new array with the same shape and type as a given array.
a = np.array([[1,2,3],[4,5,6]])
a
c = np.empty_like(a)
print(c)

[[1 2 3]
 [4 5 6]]


In [26]:
#Return a new array with the same shape and type as a given array.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#The identity array is a square array with ones on the main diagonal.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#Extract a diagonal or construct a diagonal array.
x = np.arange(9).reshape((3,3))
print(x)
np.diag(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [34]:
#k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.
print(np.diag(x, k=1))
print(np.diag(x,k=-1))

[1 5]
[3 7]


In [36]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
arr.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [44]:
#Permute the dimensions of an array.
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [48]:
#arr.T
arr.transpose((2, 0, 1)) #number of sets,number of rows and number of columns

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [52]:
x = np.array([[1,2,3]])
print(x)
np.swapaxes(x,1,0)

[[1 2 3]]


array([[1],
       [2],
       [3]])

In [57]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(x)
print(np.swapaxes(x,0,1))
print(np.swapaxes(x,0,2)) #x - input array,first axis and second axis
print(np.swapaxes(x,1,2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [58]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [63]:
np.exp(arr) 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [65]:
np.log(arr)

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.max(arr)

9

In [69]:
np.min(arr)

0

In [72]:
x = np.random.rand(8).reshape(2,4)
y = np.array([[1,2,3,5],[8,9,3,4]])

In [73]:
np.maximum(x,y)

array([[1., 2., 3., 5.],
       [8., 9., 3., 4.]])

In [74]:
np.minimum(x,y)

array([[0.71998394, 0.47165108, 0.61274941, 0.1904963 ],
       [0.63808849, 0.87477156, 0.52774189, 0.37067366]])

In [75]:
import numpy as np
arr = np.random.randn(7)

In [76]:
arr

array([-0.30423643,  0.99457679,  1.38127892, -0.70521304, -0.78119697,
       -0.41126051,  0.16968771])

In [77]:
print(arr * 5)

[-1.52118215  4.97288396  6.90639458 -3.52606522 -3.90598486 -2.05630256
  0.84843854]


In [78]:
print(arr)
remainder = np.modf(arr)
remainder

[-0.30423643  0.99457679  1.38127892 -0.70521304 -0.78119697 -0.41126051
  0.16968771]


(array([-0.30423643,  0.99457679,  0.38127892, -0.70521304, -0.78119697,
        -0.41126051,  0.16968771]), array([-0.,  0.,  1., -0., -0., -0.,  0.]))

In [81]:
whole_part = np.modf(arr)
whole_part

(array([-0.30423643,  0.99457679,  0.38127892, -0.70521304, -0.78119697,
        -0.41126051,  0.16968771]), array([-0.,  0.,  1., -0., -0., -0.,  0.]))

In [10]:
whole_part = np.modf(arr)
whole_part

(array([ 0.28654625, -0.6431968 ,  0.43131129, -0.40398919,  0.29669627,
         0.22750252,  0.24837554]), array([ 0., -0.,  0., -0.,  0.,  1.,  2.]))

In [11]:
whole_part

(array([ 0.28654625, -0.6431968 ,  0.43131129, -0.40398919,  0.29669627,
         0.22750252,  0.24837554]), array([ 0., -0.,  0., -0.,  0.,  1.,  2.]))

In [12]:
r,w = np.modf(arr)
r

array([ 0.28654625, -0.6431968 ,  0.43131129, -0.40398919,  0.29669627,
        0.22750252,  0.24837554])

In [13]:
w

array([ 0., -0.,  0., -0.,  0.,  1.,  2.])

In [14]:
a = np.modf(arr)

In [15]:
a

(array([ 0.28654625, -0.6431968 ,  0.43131129, -0.40398919,  0.29669627,
         0.22750252,  0.24837554]), array([ 0., -0.,  0., -0.,  0.,  1.,  2.]))

In [16]:
b = np.sqrt(arr)
b

C:\Users\SAKETH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.53530015,        nan, 0.65674294,        nan, 0.54469833,
       1.10792713, 1.49945841])

In [82]:
a = np.array([1,2,3])

In [85]:
#a.sum()
a.cumsum()
a.cumprod()

array([1, 2, 6], dtype=int32)

In [86]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [88]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [89]:
arr.cumsum(axis = 1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [90]:
arr.cumprod(axis = 1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [28]:
arr.cumprod(axis = 0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [91]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
arr.mean()

4.0

In [93]:
arr.var()  #var = summation of (x - x(mean)square) / n - 1

6.666666666666667

In [94]:
arr.std()   #std is square root of variance

2.581988897471611

In [111]:
arr = np.random.randn(100)
arr

array([ 7.36594690e-01, -1.85304071e+00,  1.48488887e-01, -1.75826447e+00,
        3.61961645e-01,  1.73101166e+00, -1.59273590e+00, -2.32865526e+00,
        5.53633455e-01, -2.83356979e+00, -3.09413309e-01, -9.23971864e-01,
        1.35956577e+00,  5.09005241e-01, -2.65425334e-01,  9.46869325e-02,
        1.97107603e+00, -5.18343421e-01,  2.47766517e-02,  4.57845373e-02,
       -5.33798985e-01, -1.41855052e-01, -1.12336499e-01, -3.60843910e-01,
        1.46919399e+00, -8.81868714e-01, -2.16778770e-01, -2.06559915e-01,
        4.60979526e-01,  1.91723518e-01,  5.03414767e-01, -1.22807818e+00,
       -1.68784116e+00, -5.88313734e-01,  3.26604799e-01,  2.94391644e-01,
       -1.92748498e-01,  6.08193242e-01, -2.87479396e-01,  1.42575883e+00,
       -1.31108508e-01,  8.88911433e-01, -7.12404474e-01,  5.69801069e-01,
        1.15980710e+00,  3.54283442e-01, -5.70856429e-01, -2.91696870e-01,
        1.35457737e+00, -6.81419094e-01, -3.79955432e-01, -3.70356264e-01,
        1.11470006e-01, -

In [121]:
arr<0
print(arr.any())

True


In [31]:
arr>0.sum()

SyntaxError: invalid syntax (<ipython-input-31-af5df1f35df0>, line 1)

In [115]:
(arr<0).sum() # the count of numbers in your array

50

In [116]:
#a = np.array([1,2,3])
a = np.array([True,False,True])

In [117]:
a.any() #any value True

True

In [118]:
a.all() #all it needs to have all the values

False

In [36]:
a = np.array([[1,2,3],[4,5,6]])

In [37]:
a.any()

True

In [38]:
a.all()

True

In [122]:
a = np.random.randn(2,3)

In [123]:
a

array([[-0.2626485 ,  0.30343503,  1.03890439],
       [-0.12835196,  2.21007994, -1.41650615]])

In [125]:
a.sort()

In [126]:
a

array([[-0.2626485 ,  0.30343503,  1.03890439],
       [-1.41650615, -0.12835196,  2.21007994]])

In [129]:
a.sort(1)

In [130]:
a

array([[-1.41650615, -0.12835196,  1.03890439],
       [-0.2626485 ,  0.30343503,  2.21007994]])

In [132]:
import numpy as np
a = np.array([[12,15],[10,1]])
a

array([[12, 15],
       [10,  1]])

In [133]:
a.sort(axis=0)
a

array([[10,  1],
       [12, 15]])

In [134]:
a.sort(axis = 1)
a

array([[ 1, 10],
       [12, 15]])

In [51]:
a

array([[ 1, 10],
       [12, 15]])

In [135]:
a = np.arange(10)

In [136]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.save('firstarray',a) #first array is name and a is your array

In [139]:
np.load('firstarray.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.savez('arrayarchieve',ab=a,cd=a) #savez for multiple arrays

In [141]:
c=np.load('arrayarchieve.npz')

In [142]:
c

In [152]:
c['ab']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
c['ab']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
c['cd']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
np.savez_compressed('arrayscompressed',e=a,d=a)

In [150]:
f = np.load('arrayscompressed.npz')

In [151]:
f['e']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
f['d']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
x = np.array([[1,2,3], [4, 5, 6]])

In [154]:
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [156]:
x.dot(y)  #matrix multiplication of x and y

array([[ 28,  64],
       [ 67, 181]])

In [157]:
x + y # see for formula for inverse of matrix

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [164]:
from numpy.linalg import inv

In [165]:
X = np.random.randn(5, 5)
X

array([[-0.82235602,  0.67554088, -0.86018124, -0.19843867, -0.20944636],
       [ 0.20255012, -0.17202136,  0.9292202 , -0.75565682,  0.30951084],
       [ 1.37768476, -0.08183443,  0.37885637, -0.06935056,  0.99297901],
       [-1.59546001,  0.13689301,  0.52879459,  0.6582647 ,  0.04638579],
       [ 0.10143198,  0.14256714,  0.23701083, -0.78015226,  1.99941056]])

In [167]:
inv(X)

array([[ 0.20366026,  0.08367492,  0.67826985, -0.15609359, -0.32485054],
       [ 1.98525169,  0.86626065,  1.9544194 ,  0.71628537, -0.91338731],
       [ 0.29180663,  0.84508333,  0.74061798,  0.56581313, -0.48119602],
       [-0.1367474 , -0.6272535 ,  0.64329858,  0.53051096, -0.24901822],
       [-0.2398379 , -0.41093849, -0.01055204,  0.09677333,  0.54163253]])

In [169]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7,8,9],[10,11,12]])
c = np.concatenate([arr1, arr2])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [171]:
d = np.concatenate([arr1, arr2],axis = 1)
d

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [174]:
a = np.array([(1,2,3),(3,4,5)]) 
print(a)
b = np.array([(3,4,5),(4,5,6)]) 
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [3 4 5]]
[[3 4 5]
 [4 5 6]]
[[1 2 3]
 [3 4 5]
 [3 4 5]
 [4 5 6]]
[[1 2 3 3 4 5]
 [3 4 5 4 5 6]]


In [182]:
#print(a)
a.ravel()
#a.flatten()

array([1, 2, 3, 3, 4, 5])

In [183]:
a.flatten()

array([1, 2, 3, 3, 4, 5])

In [74]:
x = np.ones([4,2])

In [75]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [76]:
x = np.array([[1,2,3],[4,5,6]])

In [77]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [79]:
a =np.arange(16).reshape(2,4,2)

In [80]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [81]:
a.cumsum(axis=0)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]]], dtype=int32)

In [85]:
a.cumsum(axis = 1)

array([[[ 0,  1],
        [ 2,  4],
        [ 6,  9],
        [12, 16]],

       [[ 8,  9],
        [18, 20],
        [30, 33],
        [44, 48]]], dtype=int32)

In [86]:
a.cumsum(axis = 2)

array([[[ 0,  1],
        [ 2,  5],
        [ 4,  9],
        [ 6, 13]],

       [[ 8, 17],
        [10, 21],
        [12, 25],
        [14, 29]]], dtype=int32)

In [84]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [95]:
import numpy as np
a= np.array([[1,25,6],[58,3,6]])

In [100]:
print(a)
print(np.argmax(a))

[[ 1 25  6]
 [58  3  6]]
3


In [101]:
np.argmin(a,axis = 0)

array([0, 1, 0], dtype=int64)

In [104]:
np.argmax(a,axis = 1)

array([1, 0], dtype=int64)

In [105]:
np.argmin(a)

0

In [110]:
#np.min(a) 
np.amin(a) 
np.max(a)    #np.min(a) or np.amin(a) same

58

In [11]:
np.max(b)

25

In [12]:
np.max(a)

58

In [13]:
np.argmin(a)

0

In [14]:
np.argmin(b)

3

In [15]:
a

array([[ 1, 25,  6],
       [58,  3,  6]])

In [16]:
b

array([[25,  6,  8],
       [ 5,  6,  9]])

In [17]:
np.argmax(a)

3

In [18]:
np.argmax(b)

0

In [19]:
np.argmin(a,axis=0)

array([0, 1, 0], dtype=int64)

In [20]:
np.argmax(a,axis=1)

array([1, 0], dtype=int64)

In [87]:
np.std(a)

1.707825127659933

In [22]:
np.std(b)

6.914156170897181

In [23]:
np.mean(a)

16.5

In [24]:
a

array([[ 1, 25,  6],
       [58,  3,  6]])

In [27]:
np.var(a)

406.25

In [28]:
np.var(b)

47.805555555555564

In [29]:
a = np.arange(10)

In [30]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b=a.T

In [32]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b = np.arange(10).reshape(1,5,2)

In [36]:
b

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [37]:
c = b.T

In [38]:
c

array([[[0],
        [2],
        [4],
        [6],
        [8]],

       [[1],
        [3],
        [5],
        [7],
        [9]]])

In [41]:
np.dot(a,b)

ValueError: shapes (10,) and (1,5,2) not aligned: 10 (dim 0) != 5 (dim 1)

In [42]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
b

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [49]:
c = np.array([[1,2,3],[4,5,6]])

In [52]:
q = np.array([[1,2,3],[4,5,6]])

In [53]:
q.ravel()

array([1, 2, 3, 4, 5, 6])

In [54]:
q.flatten()

array([1, 2, 3, 4, 5, 6])

In [55]:
q=np.array([[1,2,3],[4,5,8]])

In [56]:
q.ravel()

array([1, 2, 3, 4, 5, 8])

In [57]:
q.flatten()

array([1, 2, 3, 4, 5, 8])

In [61]:
#Ravel returns reference/view of original array whereas flatten returns copy of original array.
#If you modify the array you would notice that the value of original array also changes by using ravel.

import numpy as np 
  
# Create a numpy array 
a = np.array([(1,2,3,4),(3,1,4,2)]) 
  
# Let's print the array a 
print ("Original array:\n ")  
print(a) 
  
# To check the dimension of array (dimension =2) ( and type is numpy.ndarray ) 
print ("Dimension of array-> " , (a.ndim)) 
  
  
print("\nOutput for RAVEL \n")  
# Convert nd array to 1D array 
b = a.ravel() 
  
# Ravel only passes a view of original array to array 'b' 
print(b) 
b[0]=1000
print(b) 
  
# Note here that value of original array 'a' at also a[0][0] becomes 1000 
print(a) 
  
# Just to check the dimension i.e. 1 (and type is same numpy.ndarray ) 
print ("Dimension of array->" ,(b.ndim)) 
  
print("\nOutput for FLATTEN \n")  
  
# Convert nd array to 1D array 
c = a.flatten() 
  
# Flatten passes copy of original array to 'c' 
print(c) 
c[0]=0
print(c) 
  
# Note that by changing value of c there is no affect on value of original array 'a' 
print(a) 
  
print ("Dimension of array-> " , (c.ndim))

Original array:
 
[[1 2 3 4]
 [3 1 4 2]]
Dimension of array->  2

Output for RAVEL 

[1 2 3 4 3 1 4 2]
[1000    2    3    4    3    1    4    2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array-> 1

Output for FLATTEN 

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array->  1


In [66]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7,8,9], [10, 11, 12]])
np.concatenate([arr1,arr2],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])