In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.array(['c','m','r','t','c']) 
data

array(['c', 'm', 'r', 't', 'c'], dtype='<U1')

In [5]:
f = pd.Series(data,index = [1,2,3,4,5])

In [6]:
f

1    c
2    m
3    r
4    t
5    c
dtype: object

In [37]:
data = {'a':0,'b':1,'c':2}
data

{'a': 0, 'b': 1, 'c': 2}

In [38]:
f = pd.Series(data)

In [39]:
f

a    0
b    1
c    2
dtype: int64

In [18]:
f = pd.Series([26,12,25])

In [19]:
f

0    26
1    12
2    25
dtype: int64

In [24]:
data = [1,2,3,4,5]
d = pd.DataFrame(data)
d

0
0  1
1  2
2  3
3  4
4  5

In [33]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
d = pd.DataFrame(data,columns = ('Names','Age'),index = [1,2,3],dtype = float)
d

Names   Age
1    Alex  10.0
2     Bob  12.0
3  Clarke  13.0

In [42]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
d = pd.DataFrame(data,index=[1,2,3,4],columns = ['Name','Age'])
d

Name  Age
1    Tom   28
2   Jack   34
3  Steve   29
4  Ricky   42

In [44]:
data = [{'a': 1, 'b': 2,'c':25},{'a': 5, 'b': 10, 'c': 20}] 
d = pd.DataFrame(data,index=['first', 'second'])
d

a   b   c
first   1   2  25
second  5  10  20

In [45]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),'two': pd.Series([1, 2, 3, 4], 
    index=['a', 'b', 'c', 'd'])} 
data= pd.DataFrame(d)
data

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [47]:
obj = pd.Series([4, 7.2, -5, 3])
obj

0    4.0
1    7.2
2   -5.0
3    3.0
dtype: float64

In [48]:
obj.dtype

dtype('float64')

In [49]:
obj.values

array([ 4. ,  7.2, -5. ,  3. ])

In [50]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [51]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [52]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [53]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [57]:
obj2['b'] = 25
obj2

d     4
b    25
a    -5
c     3
dtype: int64

In [61]:
obj2[['c','d']]

c    3
d    4
dtype: int64

In [66]:
obj2[obj2>0]
obj2

d     4
b    25
a    -5
c     3
dtype: int64

In [69]:
obj2 + 2 

d     6
b    27
a    -3
c     5
dtype: int64

In [70]:
np.exp(obj2) 

d    5.459815e+01
b    7.200490e+10
a    6.737947e-03
c    2.008554e+01
dtype: float64

In [73]:
'f' in obj2  #in - Membership operators

False

In [75]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
d = pd.Series(sdata)
d

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [78]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
d= pd.Series(sdata,index = states)
d

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [79]:
d.index

Index(['California', 'Ohio', 'Oregon', 'Texas'], dtype='object')

In [80]:
d.values

array([   nan, 35000., 16000., 71000.])

In [81]:
pd.isnull(d)  #d.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [82]:
pd.notnull(d)  #d.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [83]:
d.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [84]:
d.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [85]:
obj3 = pd.Series(sdata)

In [86]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [87]:
d

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [90]:
obj3 + d
#obj3-d

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [92]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],        
'year': [2000, 2001, 2002, 2001, 2002, 2003],       
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 
f = pd.DataFrame(data)
f

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [94]:
f.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [97]:
f.tail(2)

state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [98]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [99]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four','five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [101]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [102]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [103]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [105]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [110]:
index[1:2] 

Index(['b'], dtype='object')

In [111]:
index[1] = '25'  #mutable not changeable

TypeError: Index does not support mutable operations

In [112]:
labels = pd.Index(np.arange(3))

In [113]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [114]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [115]:
obj2.index is labels #is Identity operator

True

In [116]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [117]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [122]:
frame = pd.DataFrame(np.arange(9).reshape((-1, 3)),index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [126]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [128]:
obj.drop('d')

a    0
b    1
c    2
e    4
dtype: int32

In [129]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int32

In [131]:
data = pd.DataFrame(np.arange(16).reshape((-1, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
data.drop('two',axis=1) 

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [138]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
c = data.drop(['two', 'four'], axis='columns')   

In [141]:
c

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [142]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [144]:
obj = pd.Series(np.arange(4), index=['a', 'b', 'c', 'd'])
obj

a    0
b    1
c    2
d    3
dtype: int32

In [146]:
obj[['b','c']]

b    1
c    2
dtype: int32

In [150]:
obj[[2]]  #obj[2] and obj[[2]]

c    2
dtype: int32

In [151]:
obj[2]

2

In [153]:
obj[obj > 2]

d    3
dtype: int32

In [158]:
#obj
obj['b':'c'] = 5,25 
obj

a     0
b     5
c    25
d     3
dtype: int32

In [159]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],  
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [160]:
data.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='object')

In [166]:
data[['one','three']]

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [167]:
data[:2] #data[0:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [175]:
data[data['three'] > 0]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [176]:
data = [['Tom',10],['Harry',12],['Jim',13]]
d = pd.DataFrame(data,columns = ['Name','Age'])
d

Name  Age
0    Tom   10
1  Harry   12
2    Jim   13

In [177]:
d.Name

0      Tom
1    Harry
2      Jim
Name: Name, dtype: object

In [179]:
d['Year'] = 2019,2018,2017
d

Name  Age  Year
0    Tom   10  2019
1  Harry   12  2018
2    Jim   13  2017

In [180]:
del d['Year']

In [181]:
d

Name  Age
0    Tom   10
1  Harry   12
2    Jim   13

In [183]:
data=pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],  
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [189]:
data.loc['Colorado',['one']]

one    4
Name: Colorado, dtype: int32

In [191]:
data.iloc[0]

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32

In [199]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [201]:
data.iloc[:,:3][data<5]

one  two  three
Ohio      0.0  1.0    2.0
Colorado  4.0  NaN    NaN
Utah      NaN  NaN    NaN
New York  NaN  NaN    NaN

In [203]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [204]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [205]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [210]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [211]:
df1 = pd.DataFrame(np.arange(12).reshape((3, 4)),columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [212]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [213]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [218]:
df2.loc[1,'b'] = np.nan

In [219]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [220]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [223]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [224]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [222]:
df1.add(df2, fill_value=0) 

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [225]:
df = pd.DataFrame(np.random.randn(5,3),index = ['a','c','e','f','h'],columns = ['one','two','three'])
df

one       two     three
a -0.021911  0.715278  0.392318
c  0.345188  0.395313 -0.832943
e  0.535696 -0.347082  0.110982
f  0.014112 -0.331101 -0.033842
h  0.226538 -1.257461  1.477353

In [226]:
df2 = df.reindex(['a','b','c','d','e','f','g','h'])
df2

one       two     three
a -0.021911  0.715278  0.392318
b       NaN       NaN       NaN
c  0.345188  0.395313 -0.832943
d       NaN       NaN       NaN
e  0.535696 -0.347082  0.110982
f  0.014112 -0.331101 -0.033842
g       NaN       NaN       NaN
h  0.226538 -1.257461  1.477353

In [230]:
df3 = df2.fillna(method = 'bfill',axis = 1).fillna(0)
df3

one       two     three
a -0.021911  0.715278  0.392318
b  0.000000  0.000000  0.000000
c  0.345188  0.395313 -0.832943
d  0.000000  0.000000  0.000000
e  0.535696 -0.347082  0.110982
f  0.014112 -0.331101 -0.033842
g  0.000000  0.000000  0.000000
h  0.226538 -1.257461  1.477353

In [237]:
df4 = df2.fillna(method = 'ffill',axis = 1).fillna(10)
df4

one        two      three
a  -0.021911   0.715278   0.392318
b  10.000000  10.000000  10.000000
c   0.345188   0.395313  -0.832943
d  10.000000  10.000000  10.000000
e   0.535696  -0.347082   0.110982
f   0.014112  -0.331101  -0.033842
g  10.000000  10.000000  10.000000
h   0.226538  -1.257461   1.477353

In [228]:
df2.isnull().sum()

one      3
two      3
three    3
dtype: int64

In [239]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [240]:
arr[0]

array([0, 1, 2, 3])

In [241]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [242]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
        columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [243]:
series = frame.iloc[0]

In [244]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [246]:
frame-series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9