In [1]:
import numpy as np 
# Create a numpy array 
a = np.array([(1,2,3,4),(3,1,4,2)]) 
  
# Let's print the array a 
print ("Original array:\n ")  
print(a)

Original array:
 
[[1 2 3 4]
 [3 1 4 2]]


In [4]:
print("\nOutput for RAVEL \n")  
# Convert nd array to 1D array 
b = a.ravel() 
# Ravel only passes a view of original array to array 'b' 
print(b) 
b[0]=1000
print(b) 
  
# Note here that value of original array 'a' at also a[0][0] becomes 1000 
print(a) 


Output for RAVEL 

[1000    2    3    4    3    1    4    2]
[1000    2    3    4    3    1    4    2]
[[1000    2    3    4]
 [   3    1    4    2]]


In [5]:
a

array([[1000,    2,    3,    4],
       [   3,    1,    4,    2]])

In [8]:
# Just to check the dimension i.e. 1 (and type is same numpy.ndarray ) 
print ("Dimension of array->" ,(b.ndim)) 
  
print("\nOutput for FLATTEN \n")  
  
# Convert nd array to 1D array 
c = a.flatten() 
  
# Flatten passes copy of original array to 'c' 
print(c) 
c[0]=0
print(c)
print(a)

Dimension of array-> 1

Output for FLATTEN 

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]


In [9]:
arr = np.random.randn(5, 2)
arr

array([[ 0.38997473, -0.0638854 ],
       [ 0.21078418,  0.14686197],
       [ 1.33400785,  0.82178998],
       [ 0.06309157, -0.11666004],
       [-0.59811504,  1.16740456]])

In [23]:
first, second, third = np.split(arr,[1,3])

In [24]:
first

array([[ 0.38997473, -0.0638854 ]])

In [25]:
second

array([[0.21078418, 0.14686197],
       [1.33400785, 0.82178998]])

In [26]:
third

array([[ 0.06309157, -0.11666004],
       [-0.59811504,  1.16740456]])

In [28]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)

In [29]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [30]:
arr2

array([[ 1.0951738 , -1.33418903],
       [ 1.02308874, -0.07270352],
       [ 0.0257453 ,  0.51848727]])

In [31]:
np.r_[arr1, arr2] #r_ row stacking

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 1.0951738 , -1.33418903],
       [ 1.02308874, -0.07270352],
       [ 0.0257453 ,  0.51848727]])

In [32]:
np.c_[arr1,arr2]  #c_ column stacking

array([[ 0.        ,  1.        ,  1.0951738 , -1.33418903],
       [ 2.        ,  3.        ,  1.02308874, -0.07270352],
       [ 4.        ,  5.        ,  0.0257453 ,  0.51848727]])

In [33]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [34]:
arr.repeat(3) 

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [37]:
arr.repeat([2, 3,5])

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 2])

In [39]:
arr = np.random.randn(2, 2)
arr.repeat(2, axis=1)

array([[ 0.163464  ,  0.163464  , -0.56825376, -0.56825376],
       [-0.42643616, -0.42643616, -0.2856168 , -0.2856168 ]])

In [40]:
arr

array([[ 0.163464  , -0.56825376],
       [-0.42643616, -0.2856168 ]])

In [41]:
np.tile(arr, 2)

array([[ 0.163464  , -0.56825376,  0.163464  , -0.56825376],
       [-0.42643616, -0.2856168 , -0.42643616, -0.2856168 ]])